name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Install dependencies
        shell: pixi run bash -e {0}
        run: |
          pdm install -G:all

      - name: Mypy
        shell: pixi run bash -e {0}
        run: |
          pdm run pytest
          pdm build

      - name: Test package
        shell: pixi run bash -e {0}
        run: |
          pdm run pytest
          pdm build

      - name: Build package
        shell: pixi run bash -e {0}
        run: |
          pdm build
